name: mktdata
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  get: ^4.7.3
  get_storage: ^2.1.1
  http: ^1.6.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  local_auth: ^3.0.0
  focus_detector: ^2.0.1
  flutter_native_contact_picker: ^0.0.11
  onesignal_flutter: ^5.4.1
  dio: ^5.9.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# Configuration for Native Splash Screen
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/app_icon.png
#   android: true
#   ios: true
#   android_12:
#     image: assets/app_icon.png
#     icon_background_color: "#ffffff"

# # Configuration for App Launcher Icons
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/app_icon.png"
#   min_sdk_android: 21
